<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'sortname' => 'AF'],
            ['name' => 'Aland Islands', 'sortname' => 'AX'],
            ['name' => 'Albania', 'sortname' => 'AL'],
            ['name' => 'Algeria', 'sortname' => 'DZ'],
            ['name' => 'American Samoa', 'sortname' => 'AS'],
            ['name' => 'Andorra', 'sortname' => 'AD'],
            ['name' => 'Angola', 'sortname' => 'AO'],
            ['name' => 'Anguilla', 'sortname' => 'AI'],
            ['name' => 'Antarctica', 'sortname' => 'AQ'],
            ['name' => 'Antigua and Barbuda', 'sortname' => 'AG'],
            ['name' => 'Argentina', 'sortname' => 'AR'],
            ['name' => 'Armenia', 'sortname' => 'AM'],
            ['name' => 'Aruba', 'sortname' => 'AW'],
            ['name' => 'Australia', 'sortname' => 'AU'],
            ['name' => 'Austria', 'sortname' => 'AT'],
            ['name' => 'Azerbaijan', 'sortname' => 'AZ'],
            ['name' => 'The Bahamas', 'sortname' => 'BS'],
            ['name' => 'Bahrain', 'sortname' => 'BH'],
            ['name' => 'Bangladesh', 'sortname' => 'BD'],
            ['name' => 'Barbados', 'sortname' => 'BB'],
            ['name' => 'Belarus', 'sortname' => 'BY'],
            ['name' => 'Belgium', 'sortname' => 'BE'],
            ['name' => 'Belize', 'sortname' => 'BZ'],
            ['name' => 'Benin', 'sortname' => 'BJ'],
            ['name' => 'Bermuda', 'sortname' => 'BM'],
            ['name' => 'Bhutan', 'sortname' => 'BT'],
            ['name' => 'Bolivia', 'sortname' => 'BO'],
            ['name' => 'Bosnia and Herzegovina', 'sortname' => 'BA'],
            ['name' => 'Botswana', 'sortname' => 'BW'],
            ['name' => 'Bouvet Island', 'sortname' => 'BV'],
            ['name' => 'Brazil', 'sortname' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'sortname' => 'IO'],
            ['name' => 'Brunei', 'sortname' => 'BN'],
            ['name' => 'Bulgaria', 'sortname' => 'BG'],
            ['name' => 'Burkina Faso', 'sortname' => 'BF'],
            ['name' => 'Burundi', 'sortname' => 'BI'],
            ['name' => 'Cambodia', 'sortname' => 'KH'],
            ['name' => 'Cameroon', 'sortname' => 'CM'],
            ['name' => 'Canada', 'sortname' => 'CA'],
            ['name' => 'Cape Verde', 'sortname' => 'CV'],
            ['name' => 'Cayman Islands', 'sortname' => 'KY'],
            ['name' => 'Central African Republic', 'sortname' => 'CF'],
            ['name' => 'Chad', 'sortname' => 'TD'],
            ['name' => 'Chile', 'sortname' => 'CL'],
            ['name' => 'China', 'sortname' => 'CN'],
            ['name' => 'Christmas Island', 'sortname' => 'CX'],
            ['name' => 'Cocos (Keeling) Islands', 'sortname' => 'CC'],
            ['name' => 'Colombia', 'sortname' => 'CO'],
            ['name' => 'Comoros', 'sortname' => 'KM'],
            ['name' => 'Congo', 'sortname' => 'CG'],
            ['name' => 'Democratic Republic of the Congo', 'sortname' => 'CD'],
            ['name' => 'Cook Islands', 'sortname' => 'CK'],
            ['name' => 'Costa Rica', 'sortname' => 'CR'],
            ['name' => 'Cote D\'Ivoire (Ivory Coast)', 'sortname' => 'CI'],
            ['name' => 'Croatia', 'sortname' => 'HR'],
            ['name' => 'Cuba', 'sortname' => 'CU'],
            ['name' => 'Cyprus', 'sortname' => 'CY'],
            ['name' => 'Czech Republic', 'sortname' => 'CZ'],
            ['name' => 'Denmark', 'sortname' => 'DK'],
            ['name' => 'Djibouti', 'sortname' => 'DJ'],
            ['name' => 'Dominica', 'sortname' => 'DM'],
            ['name' => 'Dominican Republic', 'sortname' => 'DO'],
            ['name' => 'Timor-Leste', 'sortname' => 'TL'],
            ['name' => 'Ecuador', 'sortname' => 'EC'],
            ['name' => 'Egypt', 'sortname' => 'EG'],
            ['name' => 'El Salvador', 'sortname' => 'SV'],
            ['name' => 'Equatorial Guinea', 'sortname' => 'GQ'],
            ['name' => 'Eritrea', 'sortname' => 'ER'],
            ['name' => 'Estonia', 'sortname' => 'EE'],
            ['name' => 'Ethiopia', 'sortname' => 'ET'],
            ['name' => 'Falkland Islands', 'sortname' => 'FK'],
            ['name' => 'Faroe Islands', 'sortname' => 'FO'],
            ['name' => 'Fiji Islands', 'sortname' => 'FJ'],
            ['name' => 'Finland', 'sortname' => 'FI'],
            ['name' => 'France', 'sortname' => 'FR'],
            ['name' => 'French Guiana', 'sortname' => 'GF'],
            ['name' => 'French Polynesia', 'sortname' => 'PF'],
            ['name' => 'French Southern Territories', 'sortname' => 'TF'],
            ['name' => 'Gabon', 'sortname' => 'GA'],
            ['name' => 'The Gambia ', 'sortname' => 'GM'],
            ['name' => 'Georgia', 'sortname' => 'GE'],
            ['name' => 'Germany', 'sortname' => 'DE'],
            ['name' => 'Ghana', 'sortname' => 'GH'],
            ['name' => 'Gibraltar', 'sortname' => 'GI'],
            ['name' => 'Greece', 'sortname' => 'GR'],
            ['name' => 'Greenland', 'sortname' => 'GL'],
            ['name' => 'Grenada', 'sortname' => 'GD'],
            ['name' => 'Guadeloupe', 'sortname' => 'GP'],
            ['name' => 'Guam', 'sortname' => 'GU'],
            ['name' => 'Guatemala', 'sortname' => 'GT'],
            ['name' => 'Guernsey', 'sortname' => 'GG'],
            ['name' => 'Guinea', 'sortname' => 'GN'],
            ['name' => 'Guinea-Bissau', 'sortname' => 'GW'],
            ['name' => 'Guyana', 'sortname' => 'GY'],
            ['name' => 'Haiti', 'sortname' => 'HT'],
            ['name' => 'Heard Island and McDonald Islands', 'sortname' => 'HM'],
            ['name' => 'Honduras', 'sortname' => 'HN'],
            ['name' => 'Hong Kong S.A.R.', 'sortname' => 'HK'],
            ['name' => 'Hungary', 'sortname' => 'HU'],
            ['name' => 'Iceland', 'sortname' => 'IS'],
            ['name' => 'India', 'sortname' => 'IN'],
            ['name' => 'Indonesia', 'sortname' => 'ID'],
            ['name' => 'Iran', 'sortname' => 'IR'],
            ['name' => 'Iraq', 'sortname' => 'IQ'],
            ['name' => 'Ireland', 'sortname' => 'IE'],
            ['name' => 'Israel', 'sortname' => 'IL'],
            ['name' => 'Italy', 'sortname' => 'IT'],
            ['name' => 'Jamaica', 'sortname' => 'JM'],
            ['name' => 'Japan', 'sortname' => 'JP'],
            ['name' => 'Jersey', 'sortname' => 'JE'],
            ['name' => 'Jordan', 'sortname' => 'JO'],
            ['name' => 'Kazakhstan', 'sortname' => 'KZ'],
            ['name' => 'Kenya', 'sortname' => 'KE'],
            ['name' => 'Kiribati', 'sortname' => 'KI'],
            ['name' => 'North Korea', 'sortname' => 'KP'],
            ['name' => 'South Korea', 'sortname' => 'KR'],
            ['name' => 'Kuwait', 'sortname' => 'KW'],
            ['name' => 'Kyrgyzstan', 'sortname' => 'KG'],
            ['name' => 'Laos', 'sortname' => 'LA'],
            ['name' => 'Latvia', 'sortname' => 'LV'],
            ['name' => 'Lebanon', 'sortname' => 'LB'],
            ['name' => 'Lesotho', 'sortname' => 'LS'],
            ['name' => 'Liberia', 'sortname' => 'LR'],
            ['name' => 'Libya', 'sortname' => 'LY'],
            ['name' => 'Liechtenstein', 'sortname' => 'LI'],
            ['name' => 'Lithuania', 'sortname' => 'LT'],
            ['name' => 'Luxembourg', 'sortname' => 'LU'],
            ['name' => 'Macau S.A.R.', 'sortname' => 'MO'],
            ['name' => 'North Macedonia', 'sortname' => 'MK'],
            ['name' => 'Madagascar', 'sortname' => 'MG'],
            ['name' => 'Malawi', 'sortname' => 'MW'],
            ['name' => 'Malaysia', 'sortname' => 'MY'],
            ['name' => 'Maldives', 'sortname' => 'MV'],
            ['name' => 'Mali', 'sortname' => 'ML'],
            ['name' => 'Malta', 'sortname' => 'MT'],
            ['name' => 'Man (Isle of)', 'sortname' => 'IM'],
            ['name' => 'Marshall Islands', 'sortname' => 'MH'],
            ['name' => 'Martinique', 'sortname' => 'MQ'],
            ['name' => 'Mauritania', 'sortname' => 'MR'],
            ['name' => 'Mauritius', 'sortname' => 'MU'],
            ['name' => 'Mayotte', 'sortname' => 'YT'],
            ['name' => 'Mexico', 'sortname' => 'MX'],
            ['name' => 'Micronesia', 'sortname' => 'FM'],
            ['name' => 'Moldova', 'sortname' => 'MD'],
            ['name' => 'Monaco', 'sortname' => 'MC'],
            ['name' => 'Mongolia', 'sortname' => 'MN'],
            ['name' => 'Montenegro', 'sortname' => 'ME'],
            ['name' => 'Montserrat', 'sortname' => 'MS'],
            ['name' => 'Morocco', 'sortname' => 'MA'],
            ['name' => 'Mozambique', 'sortname' => 'MZ'],
            ['name' => 'Myanmar', 'sortname' => 'MM'],
            ['name' => 'Namibia', 'sortname' => 'NA'],
            ['name' => 'Nauru', 'sortname' => 'NR'],
            ['name' => 'Nepal', 'sortname' => 'NP'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'sortname' => 'BQ'],
            ['name' => 'Netherlands', 'sortname' => 'NL'],
            ['name' => 'New Caledonia', 'sortname' => 'NC'],
            ['name' => 'New Zealand', 'sortname' => 'NZ'],
            ['name' => 'Nicaragua', 'sortname' => 'NI'],
            ['name' => 'Niger', 'sortname' => 'NE'],
            ['name' => 'Nigeria', 'sortname' => 'NG'],
            ['name' => 'Niue', 'sortname' => 'NU'],
            ['name' => 'Norfolk Island', 'sortname' => 'NF'],
            ['name' => 'Northern Mariana Islands', 'sortname' => 'MP'],
            ['name' => 'Norway', 'sortname' => 'NO'],
            ['name' => 'Oman', 'sortname' => 'OM'],
            ['name' => 'Pakistan', 'sortname' => 'PK'],
            ['name' => 'Palau', 'sortname' => 'PW'],
            ['name' => 'Palestinian Territory Occupied', 'sortname' => 'PS'],
            ['name' => 'Panama', 'sortname' => 'PA'],
            ['name' => 'Papua New Guinea', 'sortname' => 'PG'],
            ['name' => 'Paraguay', 'sortname' => 'PY'],
            ['name' => 'Peru', 'sortname' => 'PE'],
            ['name' => 'Philippines', 'sortname' => 'PH'],
            ['name' => 'Pitcairn Island', 'sortname' => 'PN'],
            ['name' => 'Poland', 'sortname' => 'PL'],
            ['name' => 'Portugal', 'sortname' => 'PT'],
            ['name' => 'Puerto Rico', 'sortname' => 'PR'],
            ['name' => 'Qatar', 'sortname' => 'QA'],
            ['name' => 'Reunion', 'sortname' => 'RE'],
            ['name' => 'Romania', 'sortname' => 'RO'],
            ['name' => 'Russia', 'sortname' => 'RU'],
            ['name' => 'Rwanda', 'sortname' => 'RW'],
            ['name' => 'Saint Helena', 'sortname' => 'SH'],
            ['name' => 'Saint Kitts and Nevis', 'sortname' => 'KN'],
            ['name' => 'Saint Lucia', 'sortname' => 'LC'],
            ['name' => 'Saint Pierre and Miquelon', 'sortname' => 'PM'],
            ['name' => 'Saint Vincent and the Grenadines', 'sortname' => 'VC'],
            ['name' => 'Saint-Barthelemy', 'sortname' => 'BL'],
            ['name' => 'Saint-Martin (French part)', 'sortname' => 'MF'],
            ['name' => 'Samoa', 'sortname' => 'WS'],
            ['name' => 'San Marino', 'sortname' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'sortname' => 'ST'],
            ['name' => 'Saudi Arabia', 'sortname' => 'SA'],
            ['name' => 'Senegal', 'sortname' => 'SN'],
            ['name' => 'Serbia', 'sortname' => 'RS'],
            ['name' => 'Seychelles', 'sortname' => 'SC'],
            ['name' => 'Sierra Leone', 'sortname' => 'SL'],
            ['name' => 'Singapore', 'sortname' => 'SG'],
            ['name' => 'Slovakia', 'sortname' => 'SK'],
            ['name' => 'Slovenia', 'sortname' => 'SI'],
            ['name' => 'Solomon Islands', 'sortname' => 'SB'],
            ['name' => 'Somalia', 'sortname' => 'SO'],
            ['name' => 'South Africa', 'sortname' => 'ZA'],
            ['name' => 'South Georgia', 'sortname' => 'GS'],
            ['name' => 'South Sudan', 'sortname' => 'SS'],
            ['name' => 'Spain', 'sortname' => 'ES'],
            ['name' => 'Sri Lanka', 'sortname' => 'LK'],
            ['name' => 'Sudan', 'sortname' => 'SD'],
            ['name' => 'Suriname', 'sortname' => 'SR'],
            ['name' => 'Svalbard and Jan Mayen Islands', 'sortname' => 'SJ'],
            ['name' => 'Eswatini', 'sortname' => 'SZ'],
            ['name' => 'Sweden', 'sortname' => 'SE'],
            ['name' => 'Switzerland', 'sortname' => 'CH'],
            ['name' => 'Syria', 'sortname' => 'SY'],
            ['name' => 'Taiwan', 'sortname' => 'TW'],
            ['name' => 'Tajikistan', 'sortname' => 'TJ'],
            ['name' => 'Tanzania', 'sortname' => 'TZ'],
            ['name' => 'Thailand', 'sortname' => 'TH'],
            ['name' => 'Togo', 'sortname' => 'TG'],
            ['name' => 'Tokelau', 'sortname' => 'TK'],
            ['name' => 'Tonga', 'sortname' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'sortname' => 'TT'],
            ['name' => 'Tunisia', 'sortname' => 'TN'],
            ['name' => 'Turkey', 'sortname' => 'TR'],
            ['name' => 'Turkmenistan', 'sortname' => 'TM'],
            ['name' => 'Turks and Caicos Islands', 'sortname' => 'TC'],
            ['name' => 'Tuvalu', 'sortname' => 'TV'],
            ['name' => 'Uganda', 'sortname' => 'UG'],
            ['name' => 'Ukraine', 'sortname' => 'UA'],
            ['name' => 'United Arab Emirates', 'sortname' => 'AE'],
            ['name' => 'United Kingdom', 'sortname' => 'GB'],
            ['name' => 'United States', 'sortname' => 'US'],
            ['name' => 'United States Minor Outlying Islands', 'sortname' => 'UM'],
            ['name' => 'Uruguay', 'sortname' => 'UY'],
            ['name' => 'Uzbekistan', 'sortname' => 'UZ'],
            ['name' => 'Vanuatu', 'sortname' => 'VU'],
            ['name' => 'Vatican City State (Holy See)', 'sortname' => 'VA'],
            ['name' => 'Venezuela', 'sortname' => 'VE'],
            ['name' => 'Vietnam', 'sortname' => 'VN'],
            ['name' => 'Virgin Islands (British)', 'sortname' => 'VG'],
            ['name' => 'Virgin Islands (US)', 'sortname' => 'VI'],
            ['name' => 'Wallis and Futuna Islands', 'sortname' => 'WF'],
            ['name' => 'Western Sahara', 'sortname' => 'EH'],
            ['name' => 'Yemen', 'sortname' => 'YE'],
            ['name' => 'Zambia', 'sortname' => 'ZM'],
            ['name' => 'Zimbabwe', 'sortname' => 'ZW'],
            ['name' => 'Kosovo', 'sortname' => 'XK'],
            ['name' => 'Curaçao', 'sortname' => 'CW'],
            ['name' => 'Sint Maarten (Dutch part)', 'sortname' => 'SX'],
        ];

        foreach ($countries as $country) {
            Country::firstOrCreate([
                'name' => $country['name'],
                'sortname' => $country['sortname'],
            ]);
        }

        $this->command->info('Countries table has been seeded successfully.');
    }
}
